#Программа умный попугайчик(зачем нужны переменные ?)
print('Попугайчик')
print('Кеша')
print('в')
print(2)
print('года')
print('научился говорить')
print('своё имя')
print('Кеша')
print()
print('Через')
print(2)
print('года')
print('Он научился говорить')
print('Сколько ему лет')
print()
print(4)

name = 'Кеша'
age = 2
period =2
print('Попугайчик')
print(name)
print('в')
print(age)
print('года')
print('научился говорить')
print('своё имя')
print(name)
print()
print('Через')
print(period)
print('года')
print('Он научился говорить')
print('Сколько ему лет')
print()
print(4)